### PR TITLE
add ky5047 as a new user

### PR DESCRIPTION
**Pull request by kiyoyabe**

### CODE REVIEW

**Review by PaulPrice — APPROVED** [review]
Please don't introduce changes that aren't related to the goal of the commit. This change includes two additional newlines.

**Comment by kiyoyabe** [comment]
Thank you for the review and sorry... I removed 2 new lines.

**Comment by PaulPrice** [comment]
Great, squash the commits together and you're good to go.

**Comment by kiyoyabe** [comment]
I think I squashed 2 commits. Did I do it right?

**Comment by PaulPrice** [comment]
Yep, looks good!

**Pull request merged**
